name: Github Actions Demo

on:
  push:
  workflow_dispatch:
  pull_request:
    branches: "main"
  schedule:
    - cron: "15 6 * * *"

jobs:
  Build:
    runs-on:  ubuntu-latest
    steps:
      - run: |
          echo "Event: ${{ github.event_name }}"
          echo "Branch name is ${{ github.ref }}"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Lits files in the repo
        run: |
            echo "The repo ${{ github.repository }} contains:"
            tree
        
        
